### ISSUE TITLE
is Ocamlfind needed? Does not parse itself?

### ISSUE THREAD

**Issue by nanjizal** [nadako/ml2hx#1]
In the make file it uses ocamlfind.  Ocamlfind is not provided by homebrew, it's not simple to install, my understanding is that opam would be enough, certainly I don't think Haxe compiler make files require ocamlfind since I compiled that recently.

But once installed the code would not parse itself. 

$ ./main main.ml
File "main.ml", line 2, characters 5-13:
Error: Unbound module Asttypes

Does this need to be run within the Haxe compiler src to pick up Asttypes, could you elaborate on setup?

**Comment by nadako** [comment]
To be honest, I'm not very familiar with building ocaml, so I just used the [OCamlMakefile](https://github.com/mmottl/ocaml-makefile) project, which probably uses ocamlfind, yeah. And I believe ocamlfind can be installed through opam.

As for the unbound modules - currently you need to provide `-I <dir>` arguments to provide search paths for ocaml modules (just like with usual ocaml). And yeah it might not be able to process itself yet, since there's quite a few TODOs and assertion failures

**Comment by nanjizal** [comment]
On mac you end up needing to do something like...

brew install ocaml
opam config env
opam init
opam install core utop
opam update && opam switch 4.06.0
eval \`opam config env\`
opam install ocamlfind

but order may vary slightly.  

My knowledge of Ocaml is sketchy once managed to recompile the fonts submodule to do svg paths rather than draw commands but that was long time ago more recently played with some haskell gloss, but have some books.  Was thinking, would it be useful to create two directories with stuff that build and fails so you can be sure nothing breaks as you improve it?
